default_model:
  default: resnet18_comp
  mnist: net

adv_train_iter:
  default: 7

adv_train_alpha:
  default: 0.0078431372549 # 2/255
  mnist: 0.1

adv_train_eps:
  default: 0.031372549 # 8/255
  mnist: 0.3

adv_train_trades_beta:
  default: 6.0
  mnist: 1.0
